[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "jow-api>=0.1.4",
    "psycopg2-binary>=2.9.11",
    "streamlit>=1.50.0",
]
